version: "3"
 
services:
  scouting-webserver:
    container_name: "scouting-webserver"
    env_file:
      - .env
    build: 
      context: ./webserver
      dockerfile: ./Dockerfile
    volumes:
      - './webserver:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true