version: "3"

services:
  scouting-webserver-prod:
    container_name: "production"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./webserver
      dockerfile: ./Dockerfile.prod
    expose:
      - 80
    ports:
      - "80:80/tcp"
      # - "80:80/tcp"
      # - "443:443/tcp"
    volumes:
      - ./webserver/nginx:/etc/nginx/:ro
  # ssl-proxy:
  #   image: fsouza/docker-ssl-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - DOMAIN=10.43.88.1
  #     - TARGET_PORT=8080
  #     - TARGET_HOST=scouting-webserver-prod
  #     - SSL_PORT:443