
version: "3"

services:
  scouting-webserver-nginx:
    container_name: "nginx_prod"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./webserver
      dockerfile: ./Dockerfile.nginx
    expose:
      - 80
    ports:
      - "80:80/tcp"
    volumes:
      - ./webserver/build:/usr/share/nginx/html
      - ./webserver/nginx:/etc/nginx/:ro