version: "3"

services:
  scouting-webserver-prod:
    container_name: "production"
    env_file:
      - .env
    build:
      context: ./webserver
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./webserver:/app
      # - ./webserver/build/:/app/build/
      - ./webserver/build:/nooo/build
      # - '/app/node_modules'
      # - './webserver/public:/app/public/'
      # - '/app/public/'
      # - '/app/src/'
      # - ./webserver/nginx:/etc/nginx/:ro
  # ssl-proxy:
  #   image: fsouza/docker-ssl-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - DOMAIN=10.43.88.1
  #     - TARGET_PORT=8080
  #     - TARGET_HOST=scouting-webserver-prod
  #     - SSL_PORT:443